tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f20",
        "surface-container-low": "#1c1b1c",
        "surface-container-high": "#2a2a2b",
        "surface-container-highest": "#353436",
        "surface-container-lowest": "#0e0e0f",
        "on-surface": "#e5e2e3",
        "on-surface-variant": "#b9ccb2",
        "outline-variant": "#3b4b37",
        outline: "#84967e",
        primary: "#ebffe2",
        "on-primary": "#003907",
        "primary-container": "#00ff41",
        "on-primary-container": "#007117",
        "primary-fixed": "#72ff70",
        "primary-fixed-dim": "#00e639",
        secondary: "#ffdb9d",
        "on-secondary": "#412d00",
        "secondary-container": "#feb700",
        "on-secondary-container": "#6b4b00",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#131314",
        "on-background": "#e5e2e3",
        surface: "#131314",
        "surface-variant": "#353436",
        "surface-bright": "#3a393a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        unit: "8px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "data-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "data-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
};
